name = "chat-widget"
main = "worker/index.js"  # Updated to reflect the correct file path
account_id = "${CF_ACCOUNT_ID}"
workers_dev = true
compatibility_date = "2023-10-04"

[env.production]
workers_dev = false
routes = ["lib.venuee-performance.com/chat-widget.js"]