name = "chat-widget"
main = "worker/index.js"  # Updated to reflect the correct file path
account_id = "38bb07baa14506cf0f869e5e299d5196"
workers_dev = true
compatibility_date = "2023-10-04"

[env.production]
workers_dev = false
routes = ["lib.venuee-performance.com/chat-widget.js"]